### ISSUE TITLE
Standard2019Volume not found

### ISSUE THREAD

**Issue by schmerold** [itigoag/chocolatey.microsoft-office-deployment#3]
When I run: cinst -y microsoft-office-deployment --params="'/64bit /Product:Standard2019Volume'"
I get: WARNING: Standard2019Volume not found we installed HomeBusinessRetail
Where did I go wrong?

**Comment by sbaerlocher** [comment]
I have now released a new package version that supports Office 2019.
https://chocolatey.org/packages/microsoft-office-deployment/16.0.11107.33603
