### ISSUE TITLE
Installing Office 2019 fails

### ISSUE THREAD

**Issue by olifre** [itigoag/chocolatey.microsoft-office-deployment#7]
Installation of Office 2019 fails, since the update channel chosen by default is `Broad`, which is unsupported for Office 2019. 
Trying to override the `/Channel` only changes the debug output: and activates `sharedMachine`:
https://github.com/itigoag/chocolatey.microsoft-office-deployment/blob/88d6df6e4e0d7a335062cc930eb5f6a81fd84ce6/package/tools/chocolateyinstall.ps1#L41-L43

This probably should read:
```
$channel = $PackageParameters["Channel"]
```
instead, correct?

**Comment by sbaerlocher** [comment]
Thanks for the message, I've fixed it in PR #8 now. 
@olifre Which branch should I use as default?

**Comment by olifre** [comment]
@sbaerlocher Thanks!

> Which branch should I use as default?

You mean which update channel? Since `Broad` does not work with Office 2019 and `PerpetualVL2019` (which works for Office 2019) does not work with Office 365, I wonder if the best default is an empty channel (which, at least for Office 2019, makes the deployment tool choose Microsofts default, and I'd assume this to happen with all Office versions). 
For this, however, the code would need to drop the `channel` attribute from the generated XML if `Channel` is an empty string. 

What do you think?

**Comment by sbaerlocher** [comment]
Yeah, I mean the default channel.

I can test which channel it takes if the default value is empty.

**Comment by sbaerlocher** [comment]
It works when no channel is selected.

**Comment by olifre** [comment]
Thanks for confirming and patching! 
Since I am not yet too well acquainted with Chocolatey: do you also need to manually push a new version to get Chocolatey use the fixed master?
